### ISSUE TITLE
Events not showing

### ISSUE THREAD

**Issue by ainsofttechsaqib** [jignesh13/googlecalendar#2]
Events not showing in some mobile phone 
eg vivo 1901 version 9

**Comment by jignesh13** [comment]
first check if original google calendar app if not show any event then current code not show any event because 
` public static HashMap<LocalDate, String[]> readCalendarEvent(Context context, LocalDate mintime, LocalDate maxtime) `
 return empty hashmap

otherwise there is possibility you can't accept below permission
`    <uses-permission android:name="android.permission.READ_CALENDAR"/>
`
try to accept permission from setting and restart project hope app working fine
